name: EEGToText-py28-cu128
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - h5py
  - tqdm
  - matplotlib
  - nltk
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.8.0
    - torchvision
    - torchaudio
    - transformers
    - sentence-transformers
    - fuzzy-match==0.0.1
    - rouge==1.0.0
    - evaluate
    - sacrebleu
    - jiwer
