name: EEGToText-py28-cu128
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.8
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - numpy
  - scipy
  - h5py
  - tqdm
  - matplotlib
  - nltk
  - pip
  - pip:
    - transformers
    - sentence-transformers
    - fuzzy-match==0.0.1
    - rouge==1.0.0
    - evaluate
    - sacrebleu
    - jiwer
